version: "3.8"

services:
  ui:
    build: ./packages/ui
    container_name: potluck-overdrive-ui
    env_file: .env
    volumes:
      - "static:/app/dist"
  web:
    build: ./packages/server/
    env_file: .env
    volumes:
      - "static:/app/public"
    ports:
      - "3000:3000"
    depends_on:
      - ui

volumes:
  static:
