name: "Deploy Image to Heroku"
description: "Deploys a Docker image to Heroku"
inputs:
  heroku_api_key:
    description: "This will be used for authentication. You can find it in your heroku homepage account settings"
    required: true
  heroku_email:
    description: "Email that you use with heroku"
    required: true
  heroku_app_name:
    description: "The appname to use for deploying/updating"
    required: true
  branch:
    description: "The branch that you would like to deploy to Heroku"
    default: "main"
    required: false
  docker_heroku_process_type:
    description: "Type of heroku process (web, worker, etc). This option only makes sense when usedocker enabled"
    default: "web"
    required: false
  docker_build_args:
    description: "A list of args to pass into the Docker build. This option only makes sense when usedocker enabled"
    required: false
  appdir:
    description: "Set if your app is located in a subdirectory."
    default: ""
    required: false
  healthcheck:
    description: "A URL to which a healthcheck is performed (checks for 200 request)"
    required: false
    default: ""
  checkstring:
    description: "Value to check for when conducting healthcheck request"
    required: false
    default: ""
  env_file:
    description: "Path to an localized env file"
    required: false
    default: ""
outputs:
  status:
    description: "The Success/Failure of the deployment action"
runs:
  using: "node16"
  main: "heroku-deploy.js"
