name: Deploy API to Heroku
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Start
        run: echo "Starting CI Pipeline"

      - name: Install Dependencies
        run: |
          echo "Setup Environment & Install Dependencies,"
          echo "Installing Node Dependencies."
          npm ci --prefix ./packages/api

      - name: Build API
        run: |
          echo "Running Build"
          npm run build --prefix ./packages/ui

      - name: Deploy to Heroku
        uses: ./.github/actions/heroku
        env:
          NODE_ENV: production
          TEST_VAR: ${{ env.TEST_VAR }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          VUE_APP_FIREBASE_API_KEY: ${{ secrets.VUE_APP_FIREBASE_API_KEY }}
          VUE_APP_FIREBASE_APP_ID: ${{ secrets.VUE_APP_FIREBASE_APP_ID }}
          VUE_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.VUE_APP_FIREBASE_AUTH_DOMAIN }}
          VUE_APP_FIREBASE_MEASUREMENT_ID: ${{ secrets.VUE_APP_FIREBASE_MEASUREMENT_ID }}
          VUE_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VUE_APP_FIREBASE_MESSAGING_SENDER_ID }}
          VUE_APP_FIREBASE_PROJECT_ID: ${{ secrets.VUE_APP_FIREBASE_PROJECT_ID }}
          VUE_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.VUE_APP_FIREBASE_STORAGE_BUCKET }}
          VUE_APP_SLACK_CLIENT_ID: ${{ secrets.VUE_APP_SLACK_CLIENT_ID }}
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          branch: main
          docker_build_args: |
            TEST_VAR
            VUE_APP_FIREBASE_API_KEY
            VUE_APP_FIREBASE_APP_ID
            VUE_APP_FIREBASE_AUTH_DOMAIN
            VUE_APP_FIREBASE_MEASUREMENT_ID
            VUE_APP_FIREBASE_MESSAGING_SENDER_ID
            VUE_APP_FIREBASE_PROJECT_ID
            VUE_APP_FIREBASE_STORAGE_BUCKET
            VUE_APP_SLACK_CLIENT_ID
